### ISSUE TITLE
Return to the Elements List in the Earth element redirects incorrectly

### ISSUE THREAD

**Issue by boydbsou** [boydbsou/Elemental#6]
Result: Clicking "Return to the Elements List" from the Earth element webpage redirects to the main screen webpage
Expected: Clicking "Return to the Elements List" from the Earth element webpage should redirect to the elements list webpage

**Comment by titusmaximus** [comment]
Pesticide has been sprayed

**Comment by boydbsou** [comment]
Issue has been fixed, link redirects correctly
